blank_issues_enabled: false
contact_links:
  - name: "💬 GitHub Discussions"
    url: https://github.com/onlymash/IsekaiPlayer/discussions
    about: "For Q&A, usage questions, or general discussions, please check GitHub Discussions first."
